TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  dataroot: /root/autodl-tmp/datasets/BLA_finetune_0215
  features_h5path1: /root/autodl-tmp/datasets/BLA/imgfeats/volta/genome_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: /root/autodl-tmp/datasets/BLA_finetune_0215/finetune_random/active_passive/train_ann.jsonl
  val_annotations_jsonpath: /root/autodl-tmp/datasets/BLA_finetune_0215/finetune_random/active_passive/valid_ann.jsonl
  test_annotations_jsonpath: /root/autodl-tmp/datasets/BLA_finetune_0215/finetune_random/active_passive/test_ann.jsonl
  max_seq_length: 38
  max_region_num: 36
  batch_size: 64
  train_split: ''
  train_split: train
  val_split: test
  zero_shot: True
  format: 'lmdb'