TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  dataroot: /home/xchen/datasets/BLA
  features_h5path1: /home/xchen/datasets/BLA/imgfeats/volta/genome_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  test_annotations_jsonpath: /root/autodl-tmp/datasets/BLA/annotations/coordination_captions_gruen_strict_ann.jsonl
  max_seq_length: 20
  max_region_num: 36
  batch_size: 64
  train_split: ''
  val_split: test